patreon_databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: patreon_dev
      schema: analytics
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 4
      
    prod:
      type: databricks
      catalog: patreon_prod
      schema: analytics
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      threads: 8
